Update Objetivo 2
gomares/Proyecto_IV pull request #13
Opened 2021-11-13 19:01 UTC by Xileon310

- Se añade iv.yaml y se actualiza gitignore para el lenguaje python
- Se crea manga.py para representar información #8

2021-11-13 19:10 UTC, Xileon310 commented
Por favor, linkea #8 a este PR y a su vez, linkea ese mismo issue al primer hito. Por último, revisa los cambios propuestos. Gracias de antemano.

2021-11-14 08:39 UTC, gomares commented
Todo hecho, he revisado las modificaciones a la clase manga y he de decir que están bien pero deberíamos de añadir una variable que represente el número de volúmenes de la obra. Más adelante nos ayudará también y de por sí dará información de la longitud de la obra, esto será útil para el lector.

2021-11-14 10:40 UTC, Xileon310 commented
Listo, se ha añadido el atributo del número de volúmenes y su getter correspondiente como hemos hablado.

2021-11-14 10:50 UTC, gomares commented
Perfecto, muchas gracias. Listo para revisión @JJ.

2021-11-21 19:03 UTC, JJ requested changes
Por favor, mirad lo hecho contra la lista de comprobación del objetivo.

2021-11-21 19:03 UTC, JJ commented on code/manga.py
> +		self._genres = genres
¿Dónde explica esto en #8? ¿Qué tipo tiene? ¿Cómo se valida? ¿Es una cadena o un array?

2021-11-22 13:37 UTC, Xileon310 commented on code/manga.py
> +		self._genres = genres
Listo, se ha especificado tanto el tipo y validación de genres y mangakas. También se han definido disparadores que avisarán al usuario de que no están definidos o no tienen valores correctos.

2021-11-22 13:44 UTC, Xileon310 commented
En la última actualización se han realizado los siguientes cambios:
* Se ha creado un objeto valor que representa el género de un manga. Se define en #14 y se resuelve en #f907153 . Se trata de un tipo enumerado que recoge los géneros de un manga (se han conseguido de wikipedia).
* Se han creado dos tipos de errores:
   * Mangaka --> Puesto que el atributo es una lista de strings, se debe comprobar que cada elemento de la lista es un string, ya que son nombres de personas. Esto se define en #16 y se resuelve en #4a806dc .
   * Genre --> Puesto que el atributo es una lista de valores de tipo Genre, se debe comprobar que cada elemento tiene un valor válido del enumerado Genre. Se define en #15 y se resuelve en #222b555 .
* Se ha refactorizado la descripción del issue #8 para que sea un problema y esté relacionado con una HU, en concreto con #3 .

2021-11-22 13:46 UTC, Xileon310 commented
Por favor, Abraham, linkea #14 #15 y #16 a este PR, también linkealos al primer milestone y échale un vistazo. Por mi parte diría que está listo para revisión.

2021-11-22 15:07 UTC, gomares commented
Está todo en orden. Por mi parte está listo para revisión @JJ .

2021-11-22 16:45 UTC, JJ approved these changes
Objetivo alcanzado :+1:

2021-11-22 16:45 UTC, JJ commented on code/genre.py
> +	SHONEN = 1
Aquí podías usar auto()

2021-11-22 17:02 UTC, Xileon310 commented
> Objetivo alcanzado :+1: 

Estoy llorando :')
¡Gracias!

2021-11-25 08:13 UTC, merged